version: "3.8"

services:
  db:
    image: postgres:15
    container_name: resume_parser_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: resume_parser_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  resume_parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_parser_agent
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=mistral:latest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=resume_parser_db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  pgdata:
